name: learn_github_action_unitest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest
